export const authConstants = {
  CHANGE_EXISTING_EMAIL_VALUE : "CHANGE_EXISTING_EMAIL_VALUE",
  CHECKING_SESSION: 'CHECKING_SESSION',

  TEMP_LOGIN_SUCCESS: 'TEMP_LOGIN_SUCCESS',
  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',
  RESET_REGISTER_MESSAGE: 'RESET_REGISTER_MESSAGE',
  CLEAR_ERROR: 'CLEAR_ERROR',
  USER_PROCESSING_START: 'USER_PROCESSING_START',
  USER_PROCESSING_END: 'USER_PROCESSING_END',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',

  VERIFY_REQUEST: 'USERS_VERIFY_REQUEST',
  TOKEN_VERIFYING_START: 'TOKEN_VERIFYING_START',
  TOKEN_VERIFYING_END: 'TOKEN_VERIFYING_END',
  TOKEN_VERIFYING_SUCCESS: 'TOKEN_VERIFYING_SUCCESS',
  TOKEN_VERIFYING_FAILURE: 'TOKEN_VERIFYING_FAILURE',

  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
  LOGIN_CLEAR_ERROR: 'LOGIN_CLEAR_ERROR',
  RESET_LOGIN_SUCCESS: 'RESET_LOGIN_SUCCESS',

  LOGIN_USING_FACEBOOK: 'LOGIN_USING_FACEBOOK',
  LOGIN_USING_FACEBOOK_LOADING: 'LOGIN_USING_FACEBOOK_LOADING',

  LOGIN_USING_SHOPIFY: 'LOGIN_USING_SHOPIFY',
  LOGIN_USING_SHOPIFY_LOADING: 'LOGIN_USING_SHOPIFY_LOADING',

  FORGOT_PASSWORD_LOADING: 'FORGOT_PASSWORD_LOADING',
  FORGOT_PASSWORD_REQUEST_SUCCESS: 'FORGOT_PASSWORD_REQUEST_SUCCESS',
  FORGOT_PASSWORD_REQUEST_FAILURE: 'FORGOT_PASSWORD_REQUEST_FAILURE',
  FORGOT_PASSWORD_RESET_MESSAGE: 'FORGOT_PASSWORD_RESET_MESSAGE',

  RESET_PASSWORD_REQUEST_LOADING: 'RESET_PASSWORD_REQUEST_LOADING',
  RESET_PASSWORD_REQUEST_EMAIL: 'RESET_PASSWORD_REQUEST_EMAIL',
  RESET_PASSWORD_REQUEST_SUCCESS: 'RESET_PASSWORD_REQUEST_SUCCESS',
  RESET_PASSWORD_REQUEST_FAILURE: 'RESEST_PASSWORD_REQUEST_FAILURE',
  RESET_PASSWORD_RESET_MESSAGE: 'RESET_PASSWORD_RESET_MESSAGE',

  GET_DOMAIN_REQUEST: 'GET_DOMAIN_REQUEST',
  GET_DOMAIN_SUCCESS: 'GET_DOMAIN_SUCCESS',
  GET_DOMAIN_FAILURE: 'GET_DOMAIN_FAILURE',
  ADD_DOMAIN_LOADING: 'ADD_DOMAIN_LOADING',
  GET_DOMAIN_ALREADY_EXISTS: 'GET_DOMAIN_ALREADY_EXISTS',
  RESET_DOMAIN_MESSAGE: 'RESET_DOMAIN_MESSAGE',

  AUTHENTICATE_SOCKET_IO: 'AUTHENTICATE_SOCKET_IO',

  SOCKET_CONNECTED: 'SOCKET_CONNECTED',
  SOCKET_DISCONNECTED: 'SOCKET_DISCONNECTED',
  SOCKET_RECONNECTING: 'SOCKET_RECONNECTING',
  SOCKET_CONNECTED_DATA: 'SOCKET_CONNECTED_DATA',

  UPDATING_AGENT_DATA_LOADING: 'UPDATING_AGENT_DATA_LOADING',
  UPDATE_AGENT_DATA: 'UPDATE_AGENT_DATA',
  UPDATE_COMPANY_DATA: 'UPDATE_COMPANY_DATA',
  UPDATE_COMPANY_DATA_FAILED: 'UPDATE_COMPANY_DATA_FAILED',
  UPDATE_COMPANY_DATA_RESET: 'UPDATE_COMPANY_DATA_RESET',

  UPDATING_AVATAR: 'UPDATING_AVATAR',
  UPDATING_AVATAR_SUCCESS: 'UPDATING_AVATAR_SUCCESS',
  UPDATING_AVATAR_FAILURE: 'UPDATING_AVATAR_FAILURE',
  UPDATING_AVATAR_RESET: 'UPDATING_AVATAR_RESET',

  UPDATING_AVATAR_AND_NAME: 'UPDATING_AVATAR_AND_NAME',
  UPDATING_AVATAR_AND_NAME_SUCCESS: 'UPDATING_AVATAR_AND_NAME_SUCCESS',
  UPDATING_AVATAR_AND_NAME_FAILURE: 'UPDATING_AVATAR_AND_NAME_FAILURE',
  UPDATING_AVATAR_AND_NAME_RESET: 'UPDATING_AVATAR_AND_NAME_RESET',

  // Add agent
  ADD_AGENT_LOADING: 'ADD_AGENT_LOADING',
  ADD_AGENT_SUCCESS: 'ADD_AGENT_SUCCESS',
  ADD_AGENT_FAILED: 'ADD_AGENT_FAILED',
  ADD_AGENT_RESET: 'ADD_AGENT_RESET',

  // get agents
  GET_AGENTS_LOADING: 'GET_AGENTS_LOADING',
  GET_AGENTS_SUCCESS: 'GET_AGENTS_SUCCESS',
  GET_AGENTS_FAILED: 'GET_AGENTS_FAILED',

  // CHECK if password is created
  CHECK_ADD_PASSWORD_LOADING: 'CHECK_ADD_PASSWORD_LOADING',
  CHECK_ADD_PASSWORD_SUCCESS: 'CHECK_ADD_PASSWORD_SUCCESS',
  CHECK_ADD_PASSWORD_FAILED: 'CHECK_ADD_PASSWORD_FAILED',
  // CHECK_ADD_PASSWORD_FAILED: "CHECK_ADD_PASSWORD_FAILED",

  // Add password
  ADD_PASSWORD_LOADING: 'ADD_PASSWORD_LOADING',
  ADD_PASSWORD_SUCCESS: 'ADD_PASSWORD_SUCCESS',
  ADD_PASSWORD_FAILURE: 'ADD_PASSWORD_FAILURE',
  ADD_PASSWORD_RESET: 'ADD_PASSWORD_RESET',

  // Change Password
  CHANGE_PASSWORD_LOADING: 'CHANGE_PASSWORD_LOADING',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILED: 'CHANGE_PASSWORD_FAILED',
  CHANGE_PASSWORD_RESET: 'CHANGE_PASSWORD_RESET',

  // TODO ::
  // Set Password
  SET_PASSWORD_LOADING: 'SET_PASSWORD_LOADING',
  SET_PASSWORD_SUCCESS: 'SET_PASSWORD_SUCCESS',
  SET_PASSWORD_FAILED: 'SET_PASSWORD_FAILED',
  SET_PASSWORD_RESET: 'SET_PASSWORD_RESET',

  HAS_PASSWORD_LOADING: 'HAS_PASSWORD_LOADING',
  HAS_PASSWORD_SUCCESS: 'HAS_PASSWORD_SUCCESS',
  HAS_PASSWORD_FAILED: 'HAS_PASSWORD_FAILED',

  LOGOUT: 'USER_LOGOUT',
}


export const chatConstants = {
    USER_SET_OFFLINE_FOR_VISITORS :"USER_SET_OFFLINE_FOR_VISITORS",
    USERIDS_FOR_BROADCASTING: "USERIDS_FOR_BROADCASTING",
    SEND_FIRST_MESSAGE: "SEND_FIRST_MESSAGE",
    SEND_TO_MESSAGES: "SEND_TO_MESSAGES",
    START_CHAT_LOADING: 'START_CHAT_LOADING',
    END_CHAT_LOADING: 'END_CHAT_LOADING',
    GET_MULTIPLE_PAGE_CHATS_SUCCESS: 'GET_MULTIPLE_PAGE_CHATS_SUCCESS',
  
    GET_CHAT_SUCCESS: 'GET_CHAT_SUCCESS',
    GET_CHAT_FAILURE: 'GET_CHAT_FAILURE',
  
    GET_ALL_CONVERSATIONS_LOADING: 'GET_ALL_CONVERSATIONS_LOADING',
    GET_ALL_CHATS_SUCCESS: 'GET_ALL_CHATS_SUCCESS',
    GET_ALL_CHATS_FAILURE: 'GET_ALL_CHATS_FAILURE',
  
    GET_FILTERED_CONVERSATIONS_LOADING: 'GET_FILTERED_CONVERSATIONS_LOADING',
    GET_FILTERED_CONVERSATIONS_SUCCESS: 'GET_FILTERED_CONVERSATIONS_SUCCESS',
    GET_FILTERED_CONVERSATIONS_RESET: 'GET_FILTERED_CONVERSATIONS_RESET',
  
    SEARCH_MESSAGE_SUCCESS: 'SEARCH_MESSAGE_SUCCESS',
    SEARCH_MESSAGE_FAILURE: 'SEARCH_MESSAGE_FAILURE',
    SEARCH_MESSAGE_CLEAR: 'SEARCH_MESSAGE_CLEAR',
  
    SEND_MESSAGE_FIRST: 'SEND_MESSAGE_FIRST',
    SEND_MESSAGE_FAILURE: 'SEND_MESSAGE_FAILURE',
    SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
    SEND_MESSAGE_FROM_APP_SUCCESS: 'SEND_MESSAGE_FROM_APP_SUCCESS',
    SEND_ATTACHMENT_FROM_APP_SUCCESS: 'SEND_ATTACHMENT_FROM_APP_SUCCESS',
    SEND_MESSAGE_LOADING: 'SEND_MESSAGE_LOADING',
    SENT_WHATSAPP_MESSAGE: 'SENT_WHATSAPP_MESSAGE',
  
    LIVE_CHAT_NEW_CHAT_MESSAGE: 'LIVE_CHAT_NEW_CHAT_MESSAGE',
    LIVE_CHAT_NEW_USER_REGISTERED: 'LIVE_CHAT_NEW_USER_REGISTERED',
  
    CREATE_VIDEO_CALL_REQUEST: 'CREATE_VIDEO_CALL_REQUEST',
    VIDEO_CALL_SET_RINGING: 'VIDEO_CALL_SET_RINGING',
    VIDEO_CALL_RINGING: 'VIDEO_CALL_RINGING',
    VIDEO_CALL_RINGING_NOT_ACTIVE: 'VIDEO_CALL_RINGING_NOT_ACTIVE',
    VIDEO_CALL_SET_REJECTED: 'VIDEO_CALL_SET_REJECTED',
    VIDEO_CALL_REJECT: 'VIDEO_CALL_REJECT',
    VIDEO_CALL_RECJECT_NOT_ACTIVE: 'VIDEO_CALL_RECJECT_NOT_ACTIVE',
    VIDEO_CALL_SET_ACCEPTED: 'VIDEO_CALL_SET_ACCEPTED',
    VIDEO_CALL_ACCEPT: 'VIDEO_CALL_ACCEPT',
    VIDEO_CALL_ACCEPT_NOT_ACTIVE: 'VIDEO_CALL_ACCEPT_NOT_ACTIVE',
    VIDEO_CALL_SET_ENDED: 'VIDEO_CALL_SET_ENDED',
    SHOW_VIDEO_CALL: 'SHOW_VIDEO_CALL',
    WHATSAPP_STATUS_HOOK: 'WHATSAPP_STATUS_HOOK',
    FB_MESSAGE_SENT: 'FB_MESSAGE_SENT',
    WA_SENT_MESSAGE: 'WA_SENT_MESSAGE',
  
    WA_ATTACHMENT_SEND: 'WA_ATTACHMENT_SEND',
    WA_ATTACHMENT_SENDING: 'WA_ATTACHMENT_SENDING',
    WA_ATTACHMENT_SEND_SUCCESS: 'WA_ATTACHMENT_SEND_SUCCESS',
    WA_ATTACHMENT_SEND_FAILED: 'WA_ATTACHMENT_SEND_FAILED',
  
    RESENDING_MESSAGE: 'RESENDING_MESSAGE',
  
    GET_MESSAGES_FOR_ALL_MESSAGES: 'GET_MESSAGES_FOR_ALL_MESSAGES',
    GET_MESSAGES_FROM_ALL: 'GET_MESSAGES_FROM_ALL',
  
    RECIEVED_MESSAGE_FACEBOOK: 'RECIEVED_MESSAGE_FACEBOOK',
    RECIEVED_MESSAGE_WHATSAPP: 'RECIEVED_MESSAGE_WHATSAPP',
    RESET_CHAT_PAGE: 'RESET_CHAT_PAGE',
    SET_ACTIVE_USER_ID: 'SET_ACTIVE_USER_ID',
    RESET_ACTIVE_USER: 'RESET_ACTIVE_USER',
  
    ADD_TEXT_TO_STAGE: 'ADD_TEXT_TO_STAGE',
    SET_ACTIVE_TEXT: 'SET_ACTIVE_TEXT',
    RESET_ACTIVE_TEXT: 'RESET_ACTIVE_TEXT',
  
    CONNECT_LIVE_CHAT_SOCKET: 'CONNECT_LIVE_CHAT_SOCKET',
    UPDATE_USER: 'UPDATE_USER',
  
    LIVE_CHAT_SEND_MESSAGE_FIRST: 'LIVE_CHAT_SEND_MESSAGE_FIRST',
    LIVE_CHAT_SEND_MESSAGE_SUCCESS: 'LIVE_CHAT_SEND_MESSAGE_SUCCESS',
    LIVE_CHAT_SEND_MESSAGE_FAILURE: 'LIVE_CHAT_SEND_MESSAGE_FAILURE',
    LIVE_CHAT_SEND_MESSAGE_RESEND: 'LIVE_CHAT_SEND_MESSAGE_RESEND',
  
    LIVE_CHAT_SEND_ATTACHMENT_MESSAGE_FIRST:
      'LIVE_CHAT_SEND_ATTACHMENT_MESSAGE_FIRST',
    LIVE_CHAT_SEND_ATTACHMENT_MESSAGE_SUCCESS:
      'LIVE_CHAT_SEND_ATTACHMENT_MESSAGE_SUCCESS',
    LIVE_CHAT_SEND_ATTACHMENT_MESSAGE_FAILED:
      'LIVE_CHAT_SEND_ATTACHMENT_MESSAGE_FAILED',
    LIVE_CHAT_SEND_ATTACHMENT_MESSAGE_RESEND:
      'LIVE_CHAT_SEND_ATTACHMENT_MESSAGE_RESEND',
  
    LIVE_CHAT_USER_SET_ONLINE: 'LIVE_CHAT_USER_SET_ONLINE',
    LIVE_CHAT_USER_SET_OFFLINE: 'LIVE_CHAT_USER_SET_OFFLINE',
    SET_SELECTED_CHAT_ONLINE: 'SET_SELECTED_CHAT_ONLINE',
    SET_CHATS_STATUS_ONLINE: 'SET_CHATS_STATUS_ONLINE',
  
    SET_FB_USER_INACTIVE: 'SET_FB_USER_INACTIVE',
  
    UPDATE_USER_UNREAD_COUNT: 'UPDATE_USER_UNREAD_COUNT',
    REDUCE_USER_UNREAD_COUNT: 'REDUCE_USER_UNREAD_COUNT',
  
    OPENTOK_INITIALIZE_CALL: 'OPENTOK_INITIALIZE_CALL',
    OPENTOK_CALL_END: 'OPENTOK_CALL_END',
  
    CALL_RINGING: 'CALL_RINGING',
  
    SET_BROWSER_NOTIFICATIONS: 'SET_BROWSER_NOTIFICATIONS',
    LEAVE_CONVERSATION_REQUEST: 'LEAVE_CONVERSATION_REQUEST',
    LEAVE_CONVERSATION_SUCCESS: 'LEAVE_CONVERSATION_SUCCESS',
    CHAT_OPEN_BY_OFFLINE_USER_MESSAGE: 'CHAT_OPEN_BY_OFFLINE_USER_MESSAGE',
  }